project:
  type: website
  output-dir: docs

website:
  title: "Ensaio MindMove"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: protocolo.qmd
        text: Protocolo
      - href: materiais.qmd
        text: Materiais
      - href: resultados.qmd
        text: Resultados
      - href: equipa.qmd
        text: Equipa
      - href: ia.qmd
        text: Documentação de IA
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



