---
title: "Equipa de Investigação"
---

O projeto **MindMove** foi desenvolvido no âmbito da Unidade Curricular de **Ferramentas de Produtividade**, inserida no 1º ano da **Licenciatura em Saúde Digital e Inovação Biomédica** da Faculdade de Medicina da Universidade do Porto (FMUP).

A nossa equipa colaborou de forma equilibrada na criação da estrutura do ensaio clínico, na análise de dados e na implementação da plataforma digital.

---

### Ana Sofia Bermudes Moreira
- **Afiliação Institucional:** Estudante (1º Ano), Licenciatura em Saúde Digital e Inovação Biomédica, FMUP.
- **Principais responsabilidades no Projeto:** Secções de população e estatística do protocolo, criação de diagramas (casos de uso e CONSORT) e formatação final em LaTeX/Markdown. Gestão do RedCap (Aplicação da lógica condicional, definição dos instrumentos, etc.). Desenvolvimento do site.
- **Contacto:** up202505696@up.pt

### Flávio Ferreira Lino Vieira
- **Afiliação Institucional:** Estudante (1º Ano), Licenciatura em Saúde Digital e Inovação Biomédica, FMUP.
- **Principais responsabilidades no Projeto:** Objetivos e desenho do protocolo, ética e disseminação do protocolo, diagrama de atividades da app e formatação em Word. Teste do eCRF e relatório do seu desenvolmimento. Análise Estatística em R.
- **Contacto:** up202506271@up.pt

### Gabriela Gonçalves Carneiro
- **Afiliação Institucional:** Estudante (1º Ano), Licenciatura em Saúde Digital e Inovação Biomédica, FMUP.
- **Principais responsabilidades no Projeto:** Título e racional do protocolo, diagrama de atividades do participante, CONSORT e gestão integral das referências bibliográficas. Desenvolvimento do dicionário de dados para o eCRF. Desenvolvimento da apresentação PPT.
- **Contacto:** up202505760@up.pt

### Maria Leonor Pereira Fernandes
- **Afiliação Institucional:** Estudante (1º Ano), Licenciatura em Saúde Digital e Inovação Biomédica, FMUP.
- **Principais responsabilidades no Projeto:** Secções de intervenções e outcomes do protocolo, diagrama de sequência para a app e formatação em Word. Desenvolvimento do dicionário de dados para o eCRF. Desenvolvimento do protótipo da aplicação.
- **Contacto:** up202504497@up.pt

---

**Contexto Académico:**
Este trabalho constitui um elemento de avaliação para a Unidade Curricular de Ferramentas de Produtividade.