---
title: "Resultados"
---

Nesta secção apresentamos a análise estatística do ensaio MindMove.

## 1. Características Basais da Amostra

Abaixo apresentamos a caracterização sociodemográfica e clínica inicial dos participantes.

```{r}
#| label: setup-limpeza-e-tabela
#| echo: false
#| message: false
#| warning: false

# ---- Pacotes ----
library(tidyverse)
library(here)
library(janitor)
library(gtsummary)

# ---- 1. Ler Dados Originais ----
# Lemos da pasta 'raw'
dados_originais <- read_csv(here("data", "raw", "mindmove.csv"))

# ---- 2. Limpeza e Organização ----
dados_limpos <- dados_originais |> 
  clean_names() |> 
  filter(!is.na(grupo), !is.na(idade)) |> 
  mutate(
    grupo = as.factor(grupo),
    sexo = as.factor(sexo)
  )

# dados_limpos <- dados_limpos |> drop_na() 

# ---- 3. Guardar o novo CSV ----
# Criar a pasta 'processed' caso ela não exista
if(!dir.exists(here("data", "processed"))) {
  dir.create(here("data", "processed"))
}

# Guardar em 'processed' para ser usado no site/Quarto
write_csv(dados_limpos, here("data", "processed", "mindmove_clean.csv"))

tabela1 <- dados_limpos |> 
  select(grupo, idade, sexo, phq9_baseline) |> 
  tbl_summary(
    by = grupo,
    type = list (phq9_baseline ~"continuous"),
    label = list(
      idade ~ "Idade (anos)",
      sexo ~ "Género",
      phq9_baseline ~ "PHQ-9 Inicial"
    ),
    digits = all_continuous() ~ 1
  )|> 
  add_overall() |> 
  add_p()

tabela1
```

## 2. Impacto nos Sintomas Depressivos (PHQ-9)

O gráfico seguinte ilustra a variação do outcome primário (Depressão) entre os dois grupos, às 8 semanas de intervenção.

```{r}
#| label: grafico-phq9
#| echo: false
#| message: false
#| warning: false

dados_limpos |> 
  ggplot(aes(
    x = grupo, 
    y = phq9_semana8, 
    colour = grupo)) +
  geom_boxplot(
    outlier.shape = NA, 
    width = 0.4,
    linewidth = 0.7
  ) +
  geom_jitter(
    width = 0.12, 
    alpha = 0.7, 
    size = 2.5 
  ) +
  scale_colour_manual(
    values = c(
      "intervencao" = "#2C3E50",
      "controlo"    = "#7A9B9E"
    )
  )+
  scale_x_discrete(
    labels = c("intervencao" = "Intervenção", "controlo" = "Controlo")
  )+
  labs(
    title = "Resultado MindMove: Score PHQ-9 às 8 semanas",
    x = "Grupo",
    y = "Score PHQ-9 (Depressão)"
  )+
  theme_minimal(base_size = 13) +
  theme(legend.position = "none")
```
